spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false
      username: root
      password: luxiao0314
  jpa:
    hibernate:
      ddl-auto: update  #update:每次都会更新数据库,create:每次都会清空创建
    show-sql: true
